name: Auto Post to Telegram

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  post_offer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot

      - name: Run automated posting script
        run: |
          python auto_post.py
